apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Sagar-EOL
  description: An example of a Backstage application.
  annotations:
    endoflife.date/products: angular,django
    backstage.io/kubernetes-id: carts-service
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  memberOf: [guests]
